// src/app/create-compound-set/create-compound-set.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {CompoundService} from "../compound.service";
import {FormControl, FormGroup, Validators} from "@angular/forms";
import {EmailValidators, UniversalValidators} from "ng2-validators";
import {NotifierService} from "../notifier.service";
import * as CSVParse from "csv-parse";

@Component({
  selector: 'app-create-compound-set',
  templateUrl: './create-compound-set.component.html',
  styleUrls: ['./create-compound-set.component.scss']
})
export class CreateCompoundSetComponent implements OnInit {

  isDatasetAvailable: boolean;

  @ViewChild('fileInput') fileInput;

  createForm = new FormGroup({
    email: new FormControl('', Validators.compose([Validators.required, EmailValidators.normal])),
    name: new FormControl('', Validators.required),
  });

  formErrors = {
    email: '',
    name: ''
  };

  validationMessages = {
    'email': {
      'required': 'You must enter an email',
      'email': 'You must enter a valid email'
    },
    'name': {
      'required': 'You must enter a name for your dataset',
    },
  };

  private datasetJSON: string;

  constructor(private compoundService: CompoundService, private notifier: NotifierService) { }

  ngOnInit() {
    this.isDatasetAvailable = false;
    this.createForm.valueChanges
      .debounceTime(200)
      .subscribe(data => this.onValueChanged(data));

    this.onValueChanged();
  }

  onValueChanged(data?: any) {
    if (!this.createForm) { return; }

    const form = this.createForm;

    // Validation
    for (const field in this.formErrors) {
      this.formErrors[field] = '';
      const control = form.get(field);
      if (control && control.dirty && !control.valid) {
        const messages = this.validationMessages[field];
        for (const key in control.errors) {
          this.formErrors[field] += messages[key] + ' ';
        }
      }
    }
  }

  save() {
    if (! this.createForm.valid) { return; };
    const formVal = this.createForm.value;
    if (! this.datasetJSON ) {
      this.notifier.notify('Can\'t save, there\'s no data!', 'error');
      return;
    }
    this.compoundService.create(formVal.email, formVal.name, this.datasetJSON)
      .then(msg => console.log(msg))
      .catch(err => console.log(err));
  }

  onUploadButtonClick() {
    this.fileInput.nativeElement.click();
  }

  onFileInputChange(event) {
    const fileList = event.target.files;
    if (fileList.length > 1 ) {
      this.notifier.notify('You cannot upload multiple files!', 'error');
      return;
    }
    const file = fileList[0];
    const reader = new FileReader();
    reader.onload = () => {
      const csv = reader.result;
      CSVParse(csv,
        // Set to = 201 so can provide error if over 200
        { rtrim: true, skip_empty_lines: true, to: 201, columns: ['IUPAC', 'CAS']},
        (err, compounds) => {
          if (err) {
            this.notifier.notify('An error occured while parsing your file. Please check the file is ok', 'error');
            return;
          }
          if (compounds.length < 1) {
            this.notifier.notify('There must be at least one row of data in the file.', 'error');
            return;
          }
          if (compounds.length > 200) {
            this.notifier.notify('There cannot be more than 200 rows of data in the file. ' +
              'Please split up your data into different files', 'error');
            return;
          }
          this.datasetJSON = JSON.stringify(compounds);
          this.isDatasetAvailable = true;
      });
    };

    reader.readAsText(file);
  }
}

<div class="row">
  <div class="col">
    <div class="text-center" *ngIf="!isDatasetAvailable">
      <input type="file" accept="text/csv" (change)="onFileInputChange($event)"
             style="opacity: 0; position: absolute; left:-100px" #fileInput>
      <button md-raised-button color="accent" (click)="onUploadButtonClick()">Upload dataset</button>
    </div>
    <form class="mt-3" [formGroup]="createForm" *ngIf="isDatasetAvailable">
      <div class="form-group">
        <md-input-container class="input">
          <input mdInput placeholder="Your email" type="email" formControlName="email">
        </md-input-container>
        <p style="color: red; font-size: .9rem" *ngIf="formErrors.email" class="error">
          {{ formErrors.email }}
        </p>
      </div>
      <div class="form-group">
        <md-input-container class="input">
          <input mdInput placeholder="Name" type="text" formControlName="name">
        </md-input-container>
        <p style="color: red; font-size: .9rem" *ngIf="formErrors.name" class="error">
          {{ formErrors.name }}
        </p>
      </div>
      <div class="row">
        <button md-button (click)="save()" [disabled]="!createForm.valid">Save</button>
      </div>
    </form>
  </div>
</div>

// src/scenes/CreateCompoundSet/index.jsx
import React, { Component } from 'react';
import Paper from 'material-ui/Paper';
import csv from '../../assets/csv.svg';
import RaisedButton from 'material-ui/RaisedButton';
import TextField from 'material-ui/TextField';
import FlatButton from 'material-ui/FlatButton';
import * as CSVParse from 'csv-parse';
import Compounds from '../../data/compounds';
import Snackbar from 'material-ui/Snackbar';
import Error from '../../components/Error';
import './index.css';

class CreateCompoundSet extends Component {
  constructor(props) {
    super(props);

    this.state = {
      dataset: null,
      error: null,
      datasetName: '',
      email: '',
      successMessageShown: false,
    };
  }

  handleDatasetUpload = e => {
    const fileList = e.target.files;
    if (fileList.length > 1) {
      this.setState({
        error: new Error('You cannot upload multiple files'),
      });
      return;
    }

    const file = fileList[0];
    const reader = new FileReader();
    reader.onload = () => {
      const csv = reader.result;
      CSVParse(csv,

        // Set to = 201 so can provide error if over 200
        { rtrim: true, skip_empty_lines: true, to: 201, columns: ['IUPAC', 'CAS'] },
        (err, compounds) => {
          if (err) {
            this.setState({
              error: new Error(
                'An error occured while parsing your file. Please check the formatting.'
              ),
            });
            return;
          }

          if (compounds.length < 1) {
            this.setState({
              error: new Error('There must be at least one row of data in the file.'),
            });
            return;
          }

          if (compounds.length > 200) {
            this.setState({
              error: new Error(
                'There cannot be more than 200 rows of data in the file. ' +
                'Please split the dataset up.'
              ),
            });
            return;
          }

          this.setState({
            dataset: compounds,
          });
        });
    };

    reader.readAsText(file);
  };

  handleSave = () => {
    const { dataset, email, datasetName } = this.state;
    Compounds.create({ email, name: datasetName, dataset })
      .then(res => {
        this.setState({
          dataset: null,
          email: '',
          datasetName: '',
          successMessageShown: true,
        });
      })
      .catch(err => this.setState({ error: err }));
  };

  renderUploader() {
    const { dataset } = this.state;
    if (dataset) return;

    return (
      <Paper className="form-wrapper">
        <input
          type="file"
          accept="text/csv"
          style={{ opacity: 0, position: 'absolute', left: '-100px' }}
          ref={input => this.inputElement = input}
          onChange={this.handleDatasetUpload}
        />
        <div className="header">
          <img src={csv} />
          <h1>Upload your dataset</h1>
          <p>Upload a ".csv" file with one compound per row,
            the first column containing the compound name,
            and the second column containing the CAS registry number.</p>
        </div>
        <div className="body">
          <RaisedButton
            label="Upload"
            secondary
            onTouchTap={() => this.inputElement.click() }/>
        </div>
      </Paper>
    );
  }

  onFieldChange = fieldName => e => this.setState({
    [fieldName]: e.target.value,
  });

  renderForm() {
    const { dataset } = this.state;
    if (!dataset) return;

    return (
      <Paper className="form-wrapper">
        <div className="body">
          <TextField
            fullWidth
            value={this.state.datasetName}
            onChange={this.onFieldChange('datasetName')}
            hintText="Darling Data"
            floatingLabelText="Dataset Name"
          />
          <TextField
            fullWidth
            value={this.state.email}
            onChange={this.onFieldChange('email')}
            hintText="data@star.trek"
            floatingLabelText="Your email"
          />
          <FlatButton
            label="Save"
            fullWidth
            onTouchTap={this.handleSave}
          />
        </div>
      </Paper>
    );
  }

  render() {
    const { successMessageShown, error } = this.state;

    if (error) return (
      <Error
        errorMessage={error.message}
      />
    );

    return (
      <div className="create-compound-set">
        {this.renderUploader()}
        {this.renderForm()}
        <Snackbar
          open={successMessageShown}
          message="Your dataset is processing"
          autoHideDuration={4000}
          onRequestClose={() => this.setState({ success: false })}
        />
      </div>
    );
  }
}

export default CreateCompoundSet;
